name: "chaostoolkit ubuntu CI workflow"


on:
  push:
    branches: [ dev ]

jobs:

# https://chaostoolkit.org/reference/usage/install/
  # chaostoolkit-ubuntu-latest-job:
  #   name: "chaostoolkit on ubuntu-latest"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Install chaostoolkit"
  #     run: |
  #       # Install Python
  #       sudo apt-get install python3 python3-venv
  #       # Create a virtual environment
  #       python3 -m venv ~/.venvs/chaostk 
  #       source  ~/.venvs/chaostk/bin/activate  
  #       # Install the CLI
  #       pip install -U chaostoolkit
  #       chaos --version         

# https://chaostoolkit.org/reference/tutorials/blockchain/
  chaostoolkit-ubuntu-latest-job:
    name: "Experimenting against a blockchain  chaostoolkit on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Install chaostoolkit"
      run: |
        # Install Python
        sudo apt-get install python3 python3-venv
        # Create a virtual environment
        python3 -m venv ~/.venvs/chaostk 
        source  ~/.venvs/chaostk/bin/activate  
        # Install the CLI
        pip install -U chaostoolkit
        chaos --version        
        git clone https://github.com/yolannel/CTKBlockchain
        # create the blockchain before running the experiment by running the blockchain.py fil
        python blockchain.py
        # Running the experiment
        chaos run testTransaction.json